### ISSUE TITLE
VSCode Swift: Attach to Process... command is broken

### ISSUE THREAD

**Issue by vinocher-bc** [swiftlang/vscode-swift#903] opened 2024-06-14 18:31 UTC
The VSCode `Swift: Attach to Process...` command is broken on Windows with the following error:

```
Command 'Swift: Attach to Process...' resulted in an error
Failed to find LLDB in swift toolchain
```
**To Reproduce**
On VSCode in Windows:
1. Execute `'Swift: Attach to Process...'` command
2. See error: "Failed to find LLDB in swift toolchain"

**Expected behavior**
Should allow attaching to a process

**Environment**
 - OS: Windows 11
 - Swift version:  compnerd.org Swift version 6.0-dev (LLVM 4aa2cfd77d0beee, Swift 311c55f995371dc)
Target: x86_64-unknown-windows-msvc
 - Visual Studio Code version: 1.90.1
 - vscode-swift version: v.10.1

**Additional context**
This seems like a recent regression.

**Comment by vinocher-bc** [comment] 2024-06-14 18:35
The error is from [here ](https://github.com/swiftlang/vscode-swift/blob/6de14611feb7f3ed08a6db24d7706bb1a2c05538/src/toolchain/toolchain.ts#L352-L355).
@matthewbastien, could this be related to https://github.com/swiftlang/vscode-swift/pull/890? 
Thanks.

**Comment by matthewbastien** [comment] 2024-06-14 19:04
At first glance this seems like a duplicate of #887, but I only have an arm64 Windows VM to test with which Code-LLDB does not support. @vinocher-bc are you able to build the latest version of the Swift extension from source and see if that fixes your issue?

**Comment by plemarquand** [comment] 2024-06-14 19:05
Instructions on building/installing the extension from source can be found here: https://github.com/swiftlang/vscode-swift/blob/main/CONTRIBUTING.md#building

**Comment by vinocher-bc** [comment] 2024-06-14 21:01
@plemarquand & @matthewbastien, building the extension from the latest source seems to fix this. Thanks! Is there an ETA for the next release?

**Comment by adam-fowler** [comment] 2024-06-15 06:12
I think we'll look to get another version out next week

**Closed** 2024-06-17 14:22 UTC
Labels: bug, windows, lldb
