### ISSUE TITLE
Test Explorer icons don't update on Windows

### ISSUE THREAD

**Issue by svanimpe** [swiftlang/vscode-swift#1149] opened 2024-10-18 15:24 UTC
See the screenshot below.

<img width="687" alt="error-testing" src="https://github.com/user-attachments/assets/d6dac615-7c0d-4ba5-966b-62d7141f64d4">

After running unit tests, the results appear in the Test Results pane, but the icons in the Test Explorer don't update. This did work for me on Linux, but not on Windows.

This is a template library project generated with `swift package init`.
I'm using v1.11.3 with Swift 6.0.1.

**Comment by svanimpe** [comment] 2024-10-19 13:10
Hi Paul,

I'm doing the exact same thing.

This is with swift-6.0.1-RELEASE on Windows 11.

**Comment by plemarquand** [comment] 2024-10-19 14:07
Interesting. One more question then is what version of VS Code are you running?

**Comment by svanimpe** [comment] 2024-10-19 14:11
That is 1.94.2

**Comment by plemarquand** [comment] 2024-10-21 14:18
I managed to reproduce this using Swift 6.0.1. 

The good news is this doesn't reproduce with the 6.1 (trunk development, main) [snapshot from Sept 24th](https://download.swift.org/development/windows10/swift-DEVELOPMENT-SNAPSHOT-2024-09-24-a/swift-DEVELOPMENT-SNAPSHOT-2024-09-24-a-windows10.exe). It also doesn't reproduce if you add swift-testing's `main` branch as a dependency in your Package.swift.

From my investigation on the swift-vscode side swift-testing version shipped in Swift Windows 6.0.1 is not writing to the JSON event stream. I've reached out to the swift-testing team for more info.

**Comment by plemarquand** [comment] 2024-10-21 15:05
OK a bit more information from the swift-testing team. Looks like this Windows regression was fixed by https://github.com/swiftlang/swift/pull/76564 in the 6.0.2 branch (the PR title states 6.0.1, but this is incorrect, it was merged to 6.0.2).

 A couple of options to fix this are:
- Wait for the Swift 6.0.2 release
- Use the Swift 6.1 trunk development snapshot
- Declare swift-testing as a dependency in your Package.swift

I'm going to close this as there isn't much vscode-swift can do here. Please feel free to reopen if you are still experiencing this issue with newer Swift toolchains.

**Closed by plemarquand** 2024-10-21 15:05 UTC
Labels: bug

**Comment by plemarquand** [comment] 2024-10-21 15:13
Actually, I'll keep this open and verify once 6.0.2 is released.

**Comment by svanimpe** [comment] 2024-10-21 16:29
OK. I'll just wait for 6.0.2, as this wasn't the only issue I encountered with 6.0.1.

**Comment by plemarquand** [comment] 2024-10-28 18:19
@svanimpe 6.0.2 was just released, let me know if you're still seeing the issue: https://www.swift.org/download/

**Comment by svanimpe** [comment] 2024-11-04 12:22
I no longer have this issue with 6.0.2
